#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node .husky/pre-push.js

# echo "Running lint check..."
# npx lint-staged
# if [ $? -ne 0 ]; then
#     echo "Linting failed. Push aborted."
#     exit 1
# fi
# echo "Linting passed. Proceeding with push."