#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint check..."
npm run lint
if [ $? -ne 0 ]; then
    echo "Linting failed. Commit aborted."
    exit 1
fi
echo "Linting passed. Proceeding with commit."
